using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectoIntento24.Lexer
{
    public enum TokenType
    {
        Plus,
        Minus,
        EOF,
        LessOrEqual,
        LessThan,
        ID,
        Mult,
        ORLogical,
        OREqual,
        PlusEqual,
        ANDLogical,
        ANDEqual,
        EqualEqual,
        Equal,
        NotEqual,
        Asignacion,
        RightParens,
        LeftParens,
        MinusEqual,
        LeftBracket,
        RightBracket,
        Elevate,
        ElevateEqual,
        MultEqual,
        GreaterorEqual,
        GreaterThan,
        LeftKey,
        RightKey,
        DIV,
        DivEqual,
        INCR,
        DECR,
        TBD,
        Coma,
        Semicolon,
        MODEqual,
        MOD,
        ContinueKeyword,
        OfKeyword,
        LetKeyword,
        WhileKeyword,
        VoidKeyword,
        VarKeyword,
        TrueKeyword,
        InKeyword,
        ReturnKeyword,
        IfKeyword,
        ForKeyword,
        FalseKeyword,
        ElseKeyword,
        DoKeyword,
        ConstKeyword,
        BreakKeyword,
        DosPuntos,
        Number,
        Decimal,
        FloatConstant,
        IntConstant,
        Type,
        NumberKeyword,
        BoolKeyword,
        StringKeyword,
        FunctionKeyword,
        ConsoleKeyword,
        Punto,
        LogKeyword
    }
}
